class UnauthorizedError(Exception):
    """Исключение, вызываемое при отсутсвии авторизации"""
    pass
